//package
package com.healthcarecoursework._ishanikanapathipillai_5cosc022w.model;
//imports
import java.time.LocalDate;
/**
 * Class that includes all the details relevant to the billing
 * 
 * @author inazu
 */
public class Billing {
    //Billing number
    private int billingId;
    
    //invoice price amount
    private double invoicePrice;
    
    //status of billing -paid,unpaid, pending
    private String status;
    
    //payment due data
    private LocalDate paymentDueDate;
    
    //date of payment
    private LocalDate dateOfPayment;
    
    //payment methdo - credit card, cash, bank transfer
    private String paymentMethod;
    
    //outstanding balance
    private double outstandingBalance;
    
    //description of the service
    private String description;
    
    //appointment id number
    private int appointmentId;
 
    //billing id generated by whom
    private Person generatedBy;
    
    //billing verified by
    private Person verifiedBy;
    
    //patient ID
    private int patientId;
    
    //doctor id
    private int doctorId;
    //default constructor
    public Billing(){
    }
    
    
    /**
     *
     * @param billingId id relevant to a billing  as int
     * @param invoicePrice price relevant to a billing  as double
     * @param status status of billing relevant to a billing  as String
     * @param paymentDueDate due date of payment relevant to a billing  as LocalDate
     * @param dateOfPayment date of the payment relevant to a billing  as LocalDate
     * @param paymentMethod the payment method to pay as String
     * @param outstandingBalance the amount to be paid as double
     * @param description the description of the bill as String
     * @param appointmentId the appointment id as int
     * @param generatedBy the person who generated the bill as Person
     * @param verifiedBy the person who verified the bill as Person
     * @param patientId the patient id of patient in the bill as int 
     * @param doctorId the doctor id of doctor in the bill as int
     */
    public Billing(int billingId, double invoicePrice, String status, LocalDate paymentDueDate, LocalDate dateOfPayment, String paymentMethod, double outstandingBalance, String description, int appointmentId, Person generatedBy, Person verifiedBy, int patientId, int doctorId) {
        this.billingId = billingId;
        this.invoicePrice = invoicePrice;
        this.status = status;
        this.paymentDueDate = paymentDueDate;
        this.dateOfPayment = dateOfPayment;
        this.paymentMethod = paymentMethod;
        this.outstandingBalance = outstandingBalance;
        this.description = description;
        this.appointmentId = appointmentId;
        this.generatedBy = generatedBy;
        this.verifiedBy = verifiedBy;
        this.patientId = patientId;
        this.doctorId = doctorId;
    }
    
    //billing id setter
    public void setBillingId(int billingId) {
        this.billingId = billingId;
    }
    //invoice price setter
    public void setInvoicePrice(double invoicePrice) {
        this.invoicePrice = invoicePrice;
    }
    //status setter
    public void setStatus(String status) {
        this.status = status;
    }
    //due date for payment setter
    public void setPaymentDueDate(LocalDate paymentDueDate) {
        this.paymentDueDate = paymentDueDate;
    }
    //due date setter
    public void setDateOfPayment(LocalDate dateOfPayment) {
        this.dateOfPayment = dateOfPayment;
    }
    //payment method setter
    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }
    //outstanding balance setter
    public void setOutstandingBalance(double outstandingBalance) {
        this.outstandingBalance = outstandingBalance;
    }
    //description setter
    public void setDescription(String description) {
        this.description = description;
    }
    //appointment id setter
    public void setAppointmentId(int appointmentId) {
        this.appointmentId = appointmentId;
    }
    //generated person setter
    public void setGeneratedBy(Person generatedBy) {
        this.generatedBy = generatedBy;
    }
    //verified person setter
    public void setVerifiedBy(Person verifiedBy) {
        this.verifiedBy = verifiedBy;
    }
    //patient id setter
    public void setPatientId(int patientId) {
        this.patientId = patientId;
    }
    //doctor id setter
    public void setDoctorId(int doctorId) {
        this.doctorId = doctorId;
    }
    //billing id getter
    public int getBillingId() {
        return billingId;
    }
    //invoice price getter
    public double getInvoicePrice() {
        return invoicePrice;
    }
    //status getter
    public String getStatus() {
        return status;
    }
    //payment due date getter
    public LocalDate getPaymentDueDate() {
        return paymentDueDate;
    }
    //date of payment getter
    public LocalDate getDateOfPayment() {
        return dateOfPayment;
    }
    //payment mehod getter
    public String getPaymentMethod() {
        return paymentMethod;
    }
    //outstanding balance getter
    public double getOutstandingBalance() {
        return outstandingBalance;
    }
    //description getter
    public String getDescription() {
        return description;
    }
    //appointment id getter
    public int getAppointmentId() {
        return appointmentId;
    }
    //generated person getter
    public Person getGeneratedBy() {
        return generatedBy;
    }
    //verified person getter
    public Person getVerifiedBy() {
        return verifiedBy;
    }
    //patient id getter
    public int getPatientId() {
        return patientId;
    }
    //doctor id getter
    public int getDoctorId() {
        return doctorId;
    }
    
    
}
